kind: Pod
apiVersion: v1
metadata:
  name: empty-pod
spec:
  containers:
    - name: web-server
      image: nginx:1.14
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: html
  volumes:
  - name: html
    emptyDir: {}