apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  clusterIP: 10.233.10.10
  selector:
    app: webui
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30200