apiVersion: batch/v1
kind: Job
metadata:
  name:  centos-job
spec:
  template:
    metadata:
      name: job-pod-centos
    spec:
      containers:
      - name: job-container-centos
        image: centos:7
        command:
        - bash
        args:
        - "-c"
        - "echo 'start the pod'; sleep 30; echo 'stop the pod'"
      restartPolicy: Never